#!/usr/bin/env ruby

require 'socket'
require_relative 'config'
UNICORNS = "#{File.dirname $0}/unicorns"

rand = Random.new
SOCKET.puts 'name unicorn'
SOCKET.puts 'addcmd unicorn :magic'

SOCKET.each do |msg|
  if msg =~ /^CMD /
    filenames = Dir.glob File.join UNICORNS, '*.txt'
    filename = filenames[rand.rand(filenames.size)-1]
    File.new(filename).each do |line|
      SOCKET.puts "send :#{line.chomp}"
    end
  end
end
